<?php


namespace app\modules\test_module\behaviors;

use Yii;

class AppBehavior extends \yii\base\ActionFilter
{

    public function beforeAction($action)
    {
        echo "application before behavior <br />";
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        echo "application after behavior <br />";
        $result = json_encode($result,JSON_UNESCAPED_UNICODE);
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

}