<?php
namespace app\modules\test_module\behaviors;

use Yii;
use yii\base\ActionFilter;

class IndexBehavior extends ActionFilter
{
    public function beforeAction($action)
    {
        echo "action before behavior <br />";
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        echo "action after behavior <br />";
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}